services:
  datastream:
    image: datastream:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: ${JWT_SECRET:-SUPER_SECRET_KEY}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
    ports:
      - "${CLIENT_PORT:-8080}:3000"
    volumes:
      - datastream_db:/data
      - ${MUSIC_HOST_PATH:-./apps/server/temp-music-dir}:/music:ro
    restart: unless-stopped
    networks:
      - datastream

networks:
  datastream:
    driver: bridge

volumes:
  datastream_db:
